/* Fighter Tech Tree — data
 *
 * st: 'us' | 'su' (USSR/Russia) | 'eu' (Europe) | 'rw' (rest of world)
 * t: first flight year (timeline position). row: vertical lane, loosely by
 *    manufacturer/design lineage. sub: 1 = variant sub-node hidden by the
 *    Variants toggle. dl: display date string. mfr / nat: manufacturer, nation.
 * wc: English Wikipedia article title (underscored); gk: Grokipedia slug when
 *     it differs. dsg: operator designations / license-built names.
 * Edge type 'd' = direct development · 'l' = influence/loose · 'c' = license
 * production or copy (incl. unlicensed) · q = disputed/informal.
 */
window.FIGHTER_DATA = {
  nodes: [
    // ── US Navy: Grumman lane ─────────────────────────────
    { id: "f4f", n: "F4F Wildcat", st: "us", nat: "United States", mfr: "Grumman", t: 1937, row: 0, dl: "first flight 1937",
      wc: "Grumman_F4F_Wildcat", dsg: "Royal Navy FAA: Martlet I–VI; General Motors-built airframes designated FM-1/FM-2." },
    { id: "f6f", n: "F6F Hellcat", st: "us", nat: "United States", mfr: "Grumman", t: 1942, row: 0, dl: "first flight 1942",
      wc: "Grumman_F6F_Hellcat", dsg: "Royal Navy FAA: Gannet, then Hellcat I/II." },
    { id: "f8f", n: "F8F Bearcat", st: "us", nat: "United States", mfr: "Grumman", t: 1944, row: 0, dl: "first flight 1944",
      wc: "Grumman_F8F_Bearcat" },
    { id: "f9f", n: "F9F Panther", st: "us", nat: "United States", mfr: "Grumman", t: 1947, row: 0, dl: "first flight 1947",
      wc: "Grumman_F9F_Panther" },
    { id: "f9f8", n: "F9F Cougar", st: "us", nat: "United States", mfr: "Grumman", t: 1951, row: 0, dl: "first flight 1951",
      wc: "Grumman_F-9_Cougar" },
    { id: "f11f", n: "F11F Tiger", st: "us", nat: "United States", mfr: "Grumman", t: 1954, row: 0, dl: "first flight 1954",
      wc: "Grumman_F-11_Tiger" },
    { id: "f14", n: "F-14 Tomcat", st: "us", nat: "United States", mfr: "Grumman", t: 1970, row: 0, dl: "first flight 1970",
      wc: "Grumman_F-14_Tomcat", dsg: "Only export operator: Imperial Iran (still flown by the IRIAF)." },

    // ── US Navy: Vought + McDonnell lane ──────────────────
    { id: "f4u", n: "F4U Corsair", st: "us", nat: "United States", mfr: "Vought", t: 1940, row: 1, dl: "first flight 1940",
      wc: "Vought_F4U_Corsair", dsg: "Royal Navy FAA: Corsair I–IV; license-built as Brewster F3A and Goodyear FG; French Aéronavale postwar." },
    { id: "fh1", n: "FH-1 Phantom", st: "us", nat: "United States", mfr: "McDonnell", t: 1945, row: 1, dl: "first flight 1945",
      wc: "McDonnell_FH_Phantom" },
    { id: "f2h", n: "F2H Banshee", st: "us", nat: "United States", mfr: "McDonnell", t: 1947, row: 1, dl: "first flight 1947",
      wc: "McDonnell_F2H_Banshee", dsg: "Royal Canadian Navy operated ex-USN F2H-3s." },
    { id: "f3h", n: "F3H Demon", st: "us", nat: "United States", mfr: "McDonnell", t: 1951, row: 1, dl: "first flight 1951",
      wc: "McDonnell_F3H_Demon" },
    { id: "f101", n: "F-101 Voodoo", st: "us", nat: "United States", mfr: "McDonnell", t: 1954, row: 1, dl: "first flight 1954",
      wc: "McDonnell_F-101_Voodoo", dsg: "RCAF: CF-101 Voodoo." },
    { id: "f4", n: "F-4 Phantom II", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1958, row: 1, dl: "first flight 1958",
      wc: "McDonnell_Douglas_F-4_Phantom_II",
      dsg: "RAF/RN: Phantom FG.1/FGR.2 with Rolls-Royce Spey engines; Luftwaffe: F-4F; JASDF: F-4EJ, license-built by Mitsubishi; IIAF Iran, IDF/AF Kurnass." },

    // ── US Navy: Crusader / Northrop–Hornet lane ──────────
    { id: "f8u", n: "F-8 Crusader", st: "us", nat: "United States", mfr: "Vought", t: 1955, row: 2, dl: "first flight 1955",
      wc: "Vought_F-8_Crusader", dsg: "French Aéronavale F-8E(FN) served to 1999." },
    { id: "f5a", n: "F-5A Freedom Fighter", st: "us", nat: "United States", mfr: "Northrop", t: 1959, row: 2, dl: "first flight 1959",
      wc: "Northrop_F-5", dsg: "Canadair CF-5 (Canada), NF-5 (Netherlands), CASA SF-5 (Spain); widely exported under MAP." },
    { id: "f5e", n: "F-5E Tiger II", st: "us", nat: "United States", mfr: "Northrop", t: 1972, row: 2, dl: "first flight 1972",
      wc: "Northrop_F-5", dsg: "License-assembled in Taiwan, South Korea, Switzerland." },
    { id: "yf17", n: "YF-17 Cobra", st: "us", nat: "United States", mfr: "Northrop", t: 1974.5, row: 2, dl: "first flight 1974",
      wc: "Northrop_YF-17" },
    { id: "f18", n: "F/A-18 Hornet", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1978, row: 2, dl: "first flight 1978",
      wc: "McDonnell_Douglas_F/A-18_Hornet" },
    { id: "f18ab", n: "F/A-18A/B", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1980, row: 2, sub: 1, dl: "in service 1983",
      wc: "McDonnell_Douglas_F/A-18_Hornet", dsg: "Canada: CF-188 (CF-18); Australia: A21; Spain: C.15." },
    { id: "f18cd", n: "F/A-18C/D", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1987, row: 2, sub: 1, dl: "first flight 1987",
      wc: "McDonnell_Douglas_F/A-18_Hornet", dsg: "Finland, Switzerland, Kuwait, Malaysia bought C/D-standard Hornets." },
    { id: "f18ef", n: "F/A-18E/F Super Hornet", st: "us", nat: "United States", mfr: "Boeing", t: 1995, row: 2, sub: 1, dl: "first flight 1995",
      wc: "Boeing_F/A-18E/F_Super_Hornet", dsg: "Australia: F/A-18F; EA-18G Growler is the EW derivative." },
    { id: "yf23", n: "YF-23", st: "us", nat: "United States", mfr: "Northrop/McDonnell Douglas", t: 1990, row: 1, dl: "first flight 1990",
      wc: "Northrop_YF-23", note: "Lost the ATF competition to the YF-22; two prototypes only." },

    // ── US: Lockheed lane + 5th gen ───────────────────────
    { id: "p38", n: "P-38 Lightning", st: "us", nat: "United States", mfr: "Lockheed", t: 1939, row: 3, dl: "first flight 1939",
      wc: "Lockheed_P-38_Lightning", dsg: "RAF briefly as Lightning I; F-4/F-5 photo-recon variants." },
    { id: "p80", n: "P-80 Shooting Star", st: "us", nat: "United States", mfr: "Lockheed", t: 1944, row: 3, dl: "first flight 1944",
      wc: "Lockheed_P-80_Shooting_Star", dsg: "Redesignated F-80 in 1948; T-33 trainer derivative served worldwide." },
    { id: "f94", n: "F-94 Starfire", st: "us", nat: "United States", mfr: "Lockheed", t: 1949, row: 3, dl: "first flight 1949",
      wc: "Lockheed_F-94_Starfire" },
    { id: "f104", n: "F-104 Starfighter", st: "us", nat: "United States", mfr: "Lockheed", t: 1954, row: 3, dl: "first flight 1954",
      wc: "Lockheed_F-104_Starfighter",
      dsg: "License-built: Canadair CF-104, Fokker/MBB/Messerschmitt F-104G, Mitsubishi F-104J, Aeritalia F-104S." },
    { id: "yf22", n: "YF-22", st: "us", nat: "United States", mfr: "Lockheed/Boeing/General Dynamics", t: 1990.6, row: 3, dl: "first flight 1990",
      wc: "Lockheed_YF-22" },
    { id: "f22", n: "F-22 Raptor", st: "us", nat: "United States", mfr: "Lockheed Martin", t: 1997, row: 3, dl: "first flight 1997",
      wc: "Lockheed_Martin_F-22_Raptor", note: "Export banned by US law (the Obey amendment)." },
    { id: "x35", n: "X-35", st: "us", nat: "United States", mfr: "Lockheed Martin", t: 2001, row: 3, dl: "first flight 2000",
      wc: "Lockheed_Martin_X-35" },
    { id: "f35", n: "F-35 Lightning II", st: "us", nat: "United States", mfr: "Lockheed Martin", t: 2006, row: 3, dl: "first flight 2006",
      wc: "Lockheed_Martin_F-35_Lightning_II" },
    { id: "f35a", n: "F-35A", st: "us", nat: "United States", mfr: "Lockheed Martin", t: 2008.5, row: 3, sub: 1, dl: "CTOL variant",
      wc: "Lockheed_Martin_F-35_Lightning_II", dsg: "Israel: F-35I Adir with national EW fit; Italian and Japanese FACO final assembly." },
    { id: "f35b", n: "F-35B", st: "us", nat: "United States", mfr: "Lockheed Martin", t: 2012.6, row: 3, sub: 1, dl: "STOVL, first flight 2008",
      wc: "Lockheed_Martin_F-35_Lightning_II" },
    { id: "f35c", n: "F-35C", st: "us", nat: "United States", mfr: "Lockheed Martin", t: 2016.6, row: 3, sub: 1, dl: "carrier variant, first flight 2010",
      wc: "Lockheed_Martin_F-35_Lightning_II" },
    { id: "f35i", n: "F-35I Adir", st: "us", nat: "United States / Israel", mfr: "Lockheed Martin", t: 2020.5, row: 3, sub: 1, dl: "deliveries from 2016",
      wc: "Lockheed_Martin_F-35_Lightning_II_Israeli_procurement", gk: "Lockheed_Martin_F-35_Lightning_II_Israeli_procurement", dsg: "Adir (\"Mighty One\") — IAF 140 and 116 Squadrons, Nevatim; first F-35 combat use anywhere, 2018." },

    // ── US: Bell / Republic / Convair / General Dynamics ──
    { id: "p39", n: "P-39 Airacobra", st: "us", nat: "United States", mfr: "Bell", t: 1939.5, row: 4, dl: "first flight 1938",
      wc: "Bell_P-39_Airacobra", dsg: "RAF: Airacobra I (rejected); USSR: principal user via Lend-Lease — Soviet aces scored heavily in 'Kobras'." },
    { id: "p59", n: "P-59 Airacomet", st: "us", nat: "United States", mfr: "Bell", t: 1942.7, row: 4, dl: "first flight 1942",
      wc: "Bell_P-59_Airacomet" },
    { id: "f84", n: "F-84 Thunderjet", st: "us", nat: "United States", mfr: "Republic", t: 1946, row: 4, dl: "first flight 1946",
      wc: "Republic_F-84_Thunderjet", dsg: "Supplied across NATO under MDAP." },
    { id: "f84f", n: "F-84F Thunderstreak", st: "us", nat: "United States", mfr: "Republic", t: 1950, row: 4, dl: "first flight 1950",
      wc: "Republic_F-84F_Thunderstreak" },
    { id: "f102", n: "F-102 Delta Dagger", st: "us", nat: "United States", mfr: "Convair", t: 1953.5, row: 4, dl: "first flight 1953",
      wc: "Convair_F-102_Delta_Dagger" },
    { id: "f106", n: "F-106 Delta Dart", st: "us", nat: "United States", mfr: "Convair", t: 1956, row: 4, dl: "first flight 1956",
      wc: "Convair_F-106_Delta_Dart" },
    { id: "f111", n: "F-111 Aardvark", st: "us", nat: "United States", mfr: "General Dynamics", t: 1964, row: 4, dl: "first flight 1964",
      wc: "General_Dynamics_F-111_Aardvark", dsg: "RAAF F-111C served to 2010; UK order (F-111K) cancelled." },
    { id: "f16", n: "F-16 Fighting Falcon", st: "us", nat: "United States", mfr: "General Dynamics", t: 1974, row: 4, dl: "YF-16 first flight 1974",
      wc: "General_Dynamics_F-16_Fighting_Falcon" },
    { id: "f16ab", n: "F-16A/B", st: "us", nat: "United States", mfr: "General Dynamics", t: 1978, row: 4, sub: 1, dl: "first flight 1976",
      wc: "General_Dynamics_F-16_Fighting_Falcon", dsg: "European consortium production in Belgium and the Netherlands (SABCA/Fokker); Israel: Netz." },
    { id: "f16cd", n: "F-16C/D", st: "us", nat: "United States", mfr: "General Dynamics / Lockheed Martin", t: 1984, row: 4, sub: 1, dl: "first flight 1984",
      wc: "General_Dynamics_F-16_Fighting_Falcon", dsg: "License/co-production: TAI (Turkey), KAI (Korea KF-16); Israel: Barak, F-16I Sufa." },
    { id: "f16i", n: "F-16I Sufa", st: "us", nat: "United States / Israel", mfr: "Lockheed Martin", t: 2007.5, row: 4, sub: 1, dl: "deliveries 2004–09",
      wc: "F-16I_Sufa", gk: "General_Dynamics_F-16_Fighting_Falcon_variants", dsg: "Sufa (\"Storm\") — 102 two-seaters; Israel is the largest F-16 operator outside the USAF." },
    { id: "f16ef", n: "F-16E/F Block 60", st: "us", nat: "United States", mfr: "Lockheed Martin", t: 2003, row: 4, sub: 1, dl: "first flight 2003",
      wc: "General_Dynamics_F-16_Fighting_Falcon", dsg: "UAE: 'Desert Falcon'; the current top of the line is the F-16V/Block 70." },

    // ── US: North American lane ───────────────────────────
    { id: "p40", n: "P-40 Warhawk", st: "us", nat: "United States", mfr: "Curtiss", t: 1938, row: 5, dl: "first flight 1938",
      wc: "Curtiss_P-40_Warhawk",
      dsg: "RAF/Commonwealth: Tomahawk (B/C) and Kittyhawk (D on); large Lend-Lease deliveries to the USSR; the AVG 'Flying Tigers' flew Tomahawks." },
    { id: "p51", n: "P-51 Mustang", st: "us", nat: "United States", mfr: "North American", t: 1940, row: 5, dl: "first flight 1940",
      wc: "North_American_P-51_Mustang",
      dsg: "Born from a British purchase (NA-73X): RAF Mustang Mk I–IV; A-36 Apache dive-bomber; CAC-built in Australia; redesignated F-51 in 1948." },
    { id: "fj1", n: "FJ-1 Fury", st: "us", nat: "United States", mfr: "North American", t: 1945.8, row: 5, dl: "first flight 1946",
      wc: "North_American_FJ-1_Fury" },
    { id: "f86", n: "F-86 Sabre", st: "us", nat: "United States", mfr: "North American", t: 1947.7, row: 5, dl: "first flight 1947",
      wc: "North_American_F-86_Sabre",
      dsg: "US Navy: FJ-2/-3 Fury navalized; license-built by Canadair, CAC (Avon Sabre), Mitsubishi, Fiat." },
    { id: "cl13", n: "Canadair Sabre", st: "rw", nat: "Canada", mfr: "Canadair", t: 1950.5, row: 6, dl: "first flight 1950",
      wc: "Canadair_Sabre", dsg: "RCAF Sabre Mk 2–6; supplied to the RAF, Luftwaffe, and Pakistan." },
    { id: "f100", n: "F-100 Super Sabre", st: "us", nat: "United States", mfr: "North American", t: 1953, row: 5, dl: "first flight 1953",
      wc: "North_American_F-100_Super_Sabre", dsg: "France, Denmark, Turkey, Taiwan flew MDAP F-100s." },

    // ── US: odds-and-ends lane (P-47, Avon Sabre, F-105) ──
    { id: "p47", n: "P-47 Thunderbolt", st: "us", nat: "United States", mfr: "Republic", t: 1941, row: 6, dl: "first flight 1941",
      wc: "Republic_P-47_Thunderbolt", dsg: "RAF Thunderbolt I/II in Burma; Lend-Lease to USSR, Brazil, Free France." },
    { id: "ca27", n: "CAC Avon Sabre", st: "rw", nat: "Australia", mfr: "Commonwealth Aircraft Corporation", t: 1953.4, row: 7, dl: "first flight 1953",
      wc: "CAC_Sabre", dsg: "RAAF CA-27; later transferred to Malaysia and Indonesia." },
    { id: "f105", n: "F-105 Thunderchief", st: "us", nat: "United States", mfr: "Republic", t: 1955.6, row: 6, dl: "first flight 1955",
      wc: "Republic_F-105_Thunderchief" },

    // ── US: F-15 family — singles on row 6, twins/exports row 7 ──
    { id: "f15", n: "F-15 Eagle", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1972, row: 6, dl: "first flight 1972",
      wc: "McDonnell_Douglas_F-15_Eagle" },
    { id: "f15a", n: "F-15A", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1974.5, row: 6, sub: 1, dl: "single-seat, deliveries 1974",
      wc: "McDonnell_Douglas_F-15_Eagle", dsg: "Israel: Baz — first operator to score Eagle kills." },
    { id: "f15c", n: "F-15C", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1979, row: 6, sub: 1, dl: "first flight 1979",
      wc: "McDonnell_Douglas_F-15_Eagle", dsg: "Israel: Akef; Saudi Arabia via Peace Sun." },
    { id: "f15e", n: "F-15E Strike Eagle", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1986.8, row: 6, sub: 1, dl: "first flight 1986",
      wc: "McDonnell_Douglas_F-15E_Strike_Eagle", dsg: "Israel: F-15I Ra'am; Saudi Arabia: F-15S/SA; Singapore: F-15SG; Qatar: F-15QA." },
    { id: "f15ex", n: "F-15EX Eagle II", st: "us", nat: "United States", mfr: "Boeing", t: 2021, row: 6, sub: 1, dl: "first flight 2021",
      wc: "Boeing_F-15EX_Eagle_II", dsg: "Israel: F-15IA, ordered 2024 as the Ra'am's successor." },
    { id: "f15b", n: "F-15B", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1976.5, row: 7, sub: 1, dl: "two-seat, first flew 1973 as TF-15A",
      wc: "McDonnell_Douglas_F-15_Eagle" },
    { id: "f15d", n: "F-15D", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1979.8, row: 7, sub: 1, dl: "two-seat, deliveries 1979",
      wc: "McDonnell_Douglas_F-15_Eagle" },
    { id: "f15j", n: "F-15J/DJ", st: "rw", nat: "Japan", mfr: "Mitsubishi Heavy Industries", t: 1984, row: 7, sub: 1, dl: "license production from 1981",
      wc: "Mitsubishi_F-15J", dsg: "213 built — the only full F-15 license production line outside the US." },
    { id: "f15i", n: "F-15I Ra'am", st: "us", nat: "United States / Israel", mfr: "McDonnell Douglas / Boeing", t: 1997.5, row: 7, sub: 1, dl: "deliveries 1998",
      wc: "F-15I_Ra'am", gk: "McDonnell_Douglas_F-15E_Strike_Eagle", dsg: "Ra'am (\"Thunder\") — IAF 69 Squadron, Hatzerim; 25 built." },
    { id: "f15k", n: "F-15K Slam Eagle", st: "us", nat: "United States / South Korea", mfr: "Boeing", t: 2005, row: 7, sub: 1, dl: "first flight 2005",
      wc: "McDonnell_Douglas_F-15E_Strike_Eagle", gk: "Boeing_F-15K_Slam_Eagle", dsg: "Republic of Korea Air Force; some assemblies by Korea Aerospace Industries." },

    // ── US attack lane ────────────────────────────────────
    { id: "a4", n: "A-4 Skyhawk", st: "us", nat: "United States", mfr: "Douglas", t: 1954.5, row: 8, dl: "first flight 1954",
      wc: "Douglas_A-4_Skyhawk", gk: "Douglas_A-4_Skyhawk",
      dsg: "Israel: Ayit — its J52 engine also re-powered the Sa'ar; Argentina's Skyhawks fought at the Falklands; Blue Angels mount 1974–86." },
    { id: "a6", n: "A-6 Intruder", st: "us", nat: "United States", mfr: "Grumman", t: 1960.3, row: 8, dl: "first flight 1960",
      wc: "Grumman_A-6_Intruder", gk: "Grumman_A-6_Intruder",
      dsg: "The EA-6B Prowler electronic-attack derivative outlived it by two decades, retiring in 2019." },
    { id: "a7", n: "A-7 Corsair II", st: "us", nat: "United States", mfr: "LTV (Vought)", t: 1965.7, row: 8, dl: "first flight 1965",
      wc: "LTV_A-7_Corsair_II", gk: "LTV_A-7_Corsair_II",
      dsg: "USAF A-7D drove the Navy to adopt it too; Greece flew Corsairs until 2014." },
    { id: "a10", n: "A-10 Thunderbolt II", st: "us", nat: "United States", mfr: "Fairchild Republic", t: 1972.4, row: 8, dl: "first flight 1972",
      wc: "Fairchild_Republic_A-10_Thunderbolt_II", gk: "Fairchild_Republic_A-10_Thunderbolt_II",
      note: "Built around the GAU-8 30 mm cannon; the USAF has tried to retire it for thirty years and keeps being overruled." },

    // ── UK: Hawker / EE / consortium lane ─────────────────
    { id: "hurricane", n: "Hurricane", st: "eu", nat: "United Kingdom", mfr: "Hawker", t: 1935, row: 9, dl: "first flight 1935",
      wc: "Hawker_Hurricane", dsg: "Sea Hurricane; Canadian-built by CCF; nearly 3,000 to the USSR via Lend-Lease." },
    { id: "meteor", n: "Meteor", st: "eu", nat: "United Kingdom", mfr: "Gloster", t: 1943, row: 9, dl: "first flight 1943",
      wc: "Gloster_Meteor", dsg: "Fokker-built F.8s for the Netherlands and Belgium; Argentina flew Meteors into the 1970s; Israel's first jet fighter, from 1953." },
    { id: "hunter", n: "Hunter", st: "eu", nat: "United Kingdom", mfr: "Hawker", t: 1951, row: 9, dl: "first flight 1951",
      wc: "Hawker_Hunter", dsg: "License-built by Fokker and Fairey/SABCA; served 21 air forces." },
    { id: "lightning", n: "Lightning", st: "eu", nat: "United Kingdom", mfr: "English Electric", t: 1954, row: 9, dl: "P.1 first flight 1954",
      wc: "English_Electric_Lightning" },
    { id: "jaguar", n: "Jaguar", st: "eu", nat: "UK / France", mfr: "SEPECAT (BAC/Breguet)", t: 1968, row: 9, dl: "first flight 1968",
      wc: "SEPECAT_Jaguar", dsg: "India: license-built by HAL as the Shamsher, still in service." },
        { id: "tornado", n: "Tornado IDS", st: "eu", nat: "UK / Germany / Italy", mfr: "Panavia", t: 1974.6, row: 9, dl: "first flight 1974",
      wc: "Panavia_Tornado", gk: "Panavia_Tornado",
      dsg: "RAF GR.1/GR.4; German and Italian strike and ECR versions; Saudi Arabia via Al-Yamamah." },
{ id: "tornadoadv", n: "Tornado ADV", st: "eu", nat: "UK / Germany / Italy", mfr: "Panavia", t: 1979, row: 9, dl: "first flight 1979",
      wc: "Panavia_Tornado_ADV", dsg: "RAF F.2/F.3; leased to Italy; Saudi Arabia bought the F.3." },
    { id: "typhoon", n: "Eurofighter Typhoon", st: "eu", nat: "UK / Germany / Italy / Spain", mfr: "Eurofighter GmbH", t: 1994, row: 9, dl: "first flight 1994",
      wc: "Eurofighter_Typhoon", dsg: "Luftwaffe/AMI/Ejército del Aire 'EF2000'; RAF Typhoon FGR.4." },

    // ── UK: Supermarine / de Havilland / Harrier lane ─────
    { id: "spitfire", n: "Spitfire", st: "eu", nat: "United Kingdom", mfr: "Supermarine", t: 1936, row: 10, dl: "first flight 1936",
      wc: "Supermarine_Spitfire", dsg: "Naval Seafire; flown by the USSR (Lend-Lease), USAAF, and two dozen other air arms — including Israel's 101 Squadron in 1948." },
    { id: "vampire", n: "Vampire", st: "eu", nat: "United Kingdom", mfr: "de Havilland", t: 1943.8, row: 10, dl: "first flight 1943",
      wc: "De_Havilland_Vampire", dsg: "License-built in France (SNCASE Mistral), Switzerland, Australia, India." },
    { id: "venom", n: "Venom", st: "eu", nat: "United Kingdom", mfr: "de Havilland", t: 1949, row: 10, dl: "first flight 1949",
      wc: "De_Havilland_Venom", dsg: "Swiss license production; Sea Venom / French Aquilon naval versions." },
    { id: "p1127", n: "P.1127 / Kestrel", st: "eu", nat: "United Kingdom", mfr: "Hawker Siddeley", t: 1960, row: 10, dl: "first hover 1960",
      wc: "Hawker_Siddeley_P.1127" },
    { id: "harrier", n: "Harrier GR.1", st: "eu", nat: "United Kingdom", mfr: "Hawker Siddeley", t: 1966.8, row: 10, dl: "first flight 1966",
      wc: "Hawker_Siddeley_Harrier", dsg: "USMC: AV-8A (license-assembled by McDonnell Douglas); Spain: AV-8S Matador." },
    { id: "seaharrier", n: "Sea Harrier", st: "eu", nat: "United Kingdom", mfr: "British Aerospace", t: 1978.5, row: 10, dl: "first flight 1978",
      wc: "British_Aerospace_Sea_Harrier", dsg: "Indian Navy FRS.51 flew from INS Viraat until 2016." },
    { id: "av8b", n: "AV-8B Harrier II", st: "us", nat: "United States", mfr: "McDonnell Douglas", t: 1981.8, row: 10, dl: "first flight 1981",
      wc: "McDonnell_Douglas_AV-8B_Harrier_II", dsg: "Spain: EAV-8B Matador II; Italy: AV-8B+." },
    { id: "harrier2", n: "Harrier II GR.5–GR.9", st: "eu", nat: "United Kingdom", mfr: "British Aerospace", t: 1985.4, row: 10, dl: "first flight 1985",
      wc: "British_Aerospace_Harrier_II" },

    // ── Sweden ────────────────────────────────────────────
    { id: "tunnan", n: "Saab 29 Tunnan", st: "eu", nat: "Sweden", mfr: "Saab", t: 1948, row: 11, dl: "first flight 1948",
      wc: "Saab_29_Tunnan" },
    { id: "draken", n: "Saab 35 Draken", st: "eu", nat: "Sweden", mfr: "Saab", t: 1955, row: 11, dl: "first flight 1955",
      wc: "Saab_35_Draken", dsg: "Denmark, Finland, Austria operated export Drakens." },
    { id: "viggen", n: "Saab 37 Viggen", st: "eu", nat: "Sweden", mfr: "Saab", t: 1967, row: 11, dl: "first flight 1967",
      wc: "Saab_37_Viggen" },
    { id: "gripen", n: "JAS 39 Gripen", st: "eu", nat: "Sweden", mfr: "Saab", t: 1988, row: 11, dl: "first flight 1988",
      wc: "Saab_JAS_39_Gripen", dsg: "Czech and Hungarian leases; South Africa, Brazil (Gripen E local assembly), Thailand." },

    // ── France ────────────────────────────────────────────
    { id: "ouragan", n: "Ouragan", st: "eu", nat: "France", mfr: "Dassault", t: 1949, row: 12, dl: "first flight 1949",
      wc: "Dassault_Ouragan", dsg: "India: Toofani; early IDF/AF equipment." },
    { id: "mystere4", n: "Mystère IV", st: "eu", nat: "France", mfr: "Dassault", t: 1952, row: 12, dl: "first flight 1952",
      wc: "Dassault_Myst%C3%A8re_IV", gk: "Dassault_Mystere_IV", dsg: "India: 110 for the IAF; Israel: 60 Mystère IVAs, Suez 1956 veterans." },
    { id: "supermystere", n: "Super Mystère", st: "eu", nat: "France", mfr: "Dassault", t: 1955, row: 12, dl: "first flight 1955",
      wc: "Dassault_Super_Myst%C3%A8re", gk: "Dassault_Super_Mystere", dsg: "Israel: Sa'ar, later re-engined with the A-4's J52." },
    { id: "mirage3", n: "Mirage III", st: "eu", nat: "France", mfr: "Dassault", t: 1956.8, row: 12, dl: "first flight 1956",
      wc: "Dassault_Mirage_III", dsg: "License-built in Australia (GAF) and Switzerland; Israel: Shahak." },
    { id: "mirage5", n: "Mirage 5", st: "eu", nat: "France", mfr: "Dassault", t: 1967, row: 12, dl: "first flight 1967",
      wc: "Dassault_Mirage_5", dsg: "Belgian SABCA production; the Israeli order was embargoed in 1969 — see the Nesher." },
    { id: "mirage2000", n: "Mirage 2000", st: "eu", nat: "France", mfr: "Dassault", t: 1978.5, row: 12, dl: "first flight 1978",
      wc: "Dassault_Mirage_2000", dsg: "India: Vajra; Taiwan 2000-5EI; UAE 2000-9." },
    { id: "rafale", n: "Rafale", st: "eu", nat: "France", mfr: "Dassault", t: 1986.5, row: 12, dl: "Rafale A demo 1986",
      wc: "Dassault_Rafale", dsg: "India, Egypt, Qatar, Greece, Croatia, Indonesia, UAE operate or ordered it." },

    // ── France offshoots / Israel ─────────────────────────
    { id: "miragef1", n: "Mirage F1", st: "eu", nat: "France", mfr: "Dassault", t: 1966, row: 13, dl: "first flight 1966",
      wc: "Dassault_Mirage_F1", dsg: "South Africa F1AZ/CZ; Iraq, Spain (C.14), Greece." },
    { id: "nesher", n: "IAI Nesher", st: "rw", nat: "Israel", mfr: "Israel Aircraft Industries", t: 1971, row: 14, dl: "first flight 1971",
      wc: "IAI_Nesher", dsg: "Sold to Argentina as the Dagger — fought in the Falklands; upgraded there as Finger." },
    { id: "kfir", n: "IAI Kfir", st: "rw", nat: "Israel", mfr: "Israel Aircraft Industries", t: 1973.5, row: 14, dl: "first flight 1973",
      wc: "IAI_Kfir", dsg: "US Navy/USMC leased it as the F-21A aggressor; Colombia, Ecuador, Sri Lanka." },
    { id: "lavi", n: "IAI Lavi", st: "rw", nat: "Israel", mfr: "Israel Aircraft Industries", t: 1986.9, row: 14, dl: "first flight 1986",
      wc: "IAI_Lavi", note: "Cancelled 1987 under US pressure and cost; two flying prototypes." },

    // ── Germany WWII + heirs ──────────────────────────────
    { id: "he112", n: "He 112", st: "eu", nat: "Germany", mfr: "Heinkel", t: 1935.9, row: 17, dl: "first flight 1935",
      wc: "Heinkel_He_112", gk: "Heinkel_He_112",
      note: "Lost the 1936 RLM fighter contest to the Bf 109; Heinkel never fielded a frontline piston fighter again.",
      dsg: "Exported to Romania and Spain; Japan evaluated it as the A7He1." },
    { id: "do335", n: "Do 335 Pfeil", st: "eu", nat: "Germany", mfr: "Dornier", t: 1943.8, row: 17, dl: "first flight 1943",
      wc: "Dornier_Do_335", gk: "Dornier_Do_335",
      note: "Push-pull tandem engines: the fastest piston fighter ever built, around 770 km/h — too late to matter." },
    { id: "he162", n: "He 162", st: "eu", nat: "Germany", mfr: "Heinkel", t: 1944.9, row: 17, dl: "first flight December 1944",
      wc: "Heinkel_He_162",
      note: "The Volksjäger: designed, built, and flown in under 90 days, intended for hastily trained teenage pilots." },
    { id: "bf110", n: "Bf 110", st: "eu", nat: "Germany", mfr: "Messerschmitt (BFW)", t: 1936.4, row: 18, dl: "first flight 1936",
      wc: "Messerschmitt_Bf_110", gk: "Messerschmitt_Bf_110",
      dsg: "Zerstörer heavy fighter, mauled by day in 1940; deadliest as a radar night fighter, 1943–45." },
    { id: "me163", n: "Me 163 Komet", st: "eu", nat: "Germany", mfr: "Messerschmitt", t: 1941.6, row: 18, dl: "first powered flight 1941",
      wc: "Messerschmitt_Me_163_Komet", gk: "Messerschmitt_Me_163_Komet",
      note: "The only rocket fighter ever to see combat: about eight minutes of powered flight per sortie.",
      dsg: "Japan: Mitsubishi J8M Shūsui, copied from incomplete plans after the full blueprints sank with their courier submarine." },
    { id: "bf109", n: "Bf 109", st: "eu", nat: "Germany", mfr: "Messerschmitt (BFW)", t: 1935.5, row: 19, dl: "first flight 1935",
      wc: "Messerschmitt_Bf_109", dsg: "License/derivative production in Spain (HA-1112) and Czechoslovakia (Avia S-99/S-199); Finnish, Romanian, Hungarian service." },
    { id: "fw190", n: "Fw 190", st: "eu", nat: "Germany", mfr: "Focke-Wulf", t: 1939.4, row: 21, dl: "first flight 1939",
      wc: "Focke-Wulf_Fw_190" },
    { id: "me262", n: "Me 262", st: "eu", nat: "Germany", mfr: "Messerschmitt", t: 1942, row: 19, dl: "first jet flight 1942",
      wc: "Messerschmitt_Me_262", note: "First operational jet fighter." },
    { id: "ta152", n: "Ta 152", st: "eu", nat: "Germany", mfr: "Focke-Wulf", t: 1944, row: 21, dl: "first flight 1944",
      wc: "Focke-Wulf_Ta_152" },
    { id: "s92", n: "Avia S-92", st: "eu", nat: "Czechoslovakia", mfr: "Avia", t: 1945.9, row: 20, dl: "first flight 1946",
      wc: "Avia_S-92", note: "Czechoslovak-built Me 262 from leftover jigs and parts." },
    { id: "s199", n: "Avia S-199", st: "eu", nat: "Czechoslovakia", mfr: "Avia", t: 1947.5, row: 20, dl: "first flight 1947",
      wc: "Avia_S-199", dsg: "Israel: the IDF/AF's first fighter, nicknamed 'Sakeen' (knife) — and less politely 'Mule'." },
    { id: "ha1112", n: "HA-1112 Buchón", st: "eu", nat: "Spain", mfr: "Hispano Aviación", t: 1954.7, row: 20, dl: "Merlin-engined 1954",
      wc: "Hispano_Aviaci%C3%B3n_HA-1112", gk: "Hispano_Aviacion_HA-1112" },

    // ── Egypt / Iran lane ─────────────────────────────────
    { id: "ha300", n: "Helwan HA-300", st: "rw", nat: "Egypt", mfr: "Helwan Aircraft Factory", t: 1964, row: 16, dl: "first flight 1964",
      wc: "Helwan_HA-300", gk: "Helwan_HA-300",
      note: "Willy Messerschmitt's last fighter design; cancelled 1969 when Egypt's money and Soviet patience ran out.",
      dsg: "Airframe by Messerschmitt's team at Helwan; E-300 engine by Ferdinand Brandner's ex-Junkers group." },
    { id: "marut", n: "HF-24 Marut", st: "rw", nat: "India", mfr: "Hindustan Aeronautics (HAL)", t: 1961, row: 22, dl: "first flight 1961",
      wc: "HAL_HF-24_Marut", note: "Designed under Kurt Tank, late of Focke-Wulf." },
    { id: "cheetah", n: "Atlas Cheetah", st: "rw", nat: "South Africa", mfr: "Atlas Aircraft", t: 1986.2, row: 15, dl: "unveiled 1986",
      wc: "Atlas_Cheetah", dsg: "Survivors sold to Ecuador and to US contractor Draken International." },
    { id: "tejas", n: "HAL Tejas", st: "rw", nat: "India", mfr: "Hindustan Aeronautics (HAL)", t: 2001, row: 22, dl: "first flight 2001",
      wc: "HAL_Tejas" },

    // ── Japan / rest of Asia ──────────────────────────────
    { id: "a5m", n: "A5M Claude", st: "rw", nat: "Japan", mfr: "Mitsubishi", t: 1935.1, row: 23, dl: "first flight 1935",
      wc: "Mitsubishi_A5M", dsg: "Allied reporting name 'Claude'; IJN Type 96 carrier fighter — the world's first monoplane carrier fighter in service." },
    { id: "a6m", n: "A6M Zero", st: "rw", nat: "Japan", mfr: "Mitsubishi", t: 1939.2, row: 23, dl: "first flight 1939",
      wc: "Mitsubishi_A6M_Zero", dsg: "Allied reporting name 'Zeke'; Nakajima built the majority of airframes." },
    { id: "j2m", n: "J2M Raiden", st: "rw", nat: "Japan", mfr: "Mitsubishi", t: 1942.2, row: 23, dl: "first flight 1942",
      wc: "Mitsubishi_J2M_Raiden", dsg: "Allied reporting name 'Jack'; IJN local-interceptor counterpart to the carrier Zero." },
    { id: "n1k2", n: "N1K Shiden-Kai", st: "rw", nat: "Japan", mfr: "Kawanishi", t: 1944, row: 24, dl: "N1K1-J 1942 · N1K2-J 1944",
      wc: "Kawanishi_N1K", dsg: "Allied reporting name 'George'; developed from the N1K Kyofu floatplane fighter." },
    { id: "ki27", n: "Ki-27", st: "rw", nat: "Japan", mfr: "Nakajima", t: 1936.8, row: 25, dl: "first flight 1936",
      wc: "Nakajima_Ki-27", dsg: "Allied reporting name 'Nate'; IJA Type 97 fighter." },
    { id: "ki43", n: "Ki-43 Hayabusa", st: "rw", nat: "Japan", mfr: "Nakajima", t: 1939, row: 25, dl: "first flight 1939",
      wc: "Nakajima_Ki-43_Hayabusa", dsg: "Allied reporting name 'Oscar' — the IJA's most-produced fighter." },
    { id: "ki44", n: "Ki-44 Shōki", st: "rw", nat: "Japan", mfr: "Nakajima", t: 1940.6, row: 26, dl: "first flight 1940",
      wc: "Nakajima_Ki-44_Sh%C5%8Dki", gk: "Nakajima_Ki-44", dsg: "Allied reporting name 'Tojo'; speed-and-climb interceptor heresy in a maneuverability air force." },
    { id: "ki61", n: "Ki-61 Hien", st: "rw", nat: "Japan", mfr: "Kawasaki", t: 1941.9, row: 27, dl: "first flight 1941",
      wc: "Kawasaki_Ki-61", dsg: "Allied reporting name 'Tony' — initially misidentified as a license-built Bf 109 or an Italian type." },
    { id: "ki100", n: "Ki-100", st: "rw", nat: "Japan", mfr: "Kawasaki", t: 1945.1, row: 27, dl: "first flight 1945",
      wc: "Kawasaki_Ki-100", dsg: "Ki-61-II airframes finished with the Ha-112 radial after B-29s burned the Ha-140 engine plant." },
    { id: "ki84", n: "Ki-84 Hayate", st: "rw", nat: "Japan", mfr: "Nakajima", t: 1943.3, row: 25, dl: "first flight 1943",
      wc: "Nakajima_Ki-84", dsg: "Allied reporting name 'Frank'." },
    { id: "f1jp", n: "Mitsubishi F-1", st: "rw", nat: "Japan", mfr: "Mitsubishi", t: 1975, row: 23, dl: "first flight 1975",
      wc: "Mitsubishi_F-1", note: "Japan's first postwar domestic combat jet, developed from the T-2 trainer." },
    { id: "fck1", n: "F-CK-1 Ching-kuo", st: "rw", nat: "Taiwan", mfr: "AIDC", t: 1989, row: 28, dl: "first flight 1989",
      wc: "AIDC_F-CK-1_Ching-kuo" },
    { id: "f2", n: "Mitsubishi F-2", st: "rw", nat: "Japan", mfr: "Mitsubishi / Lockheed Martin", t: 2000, row: 23, dl: "first flight 1995",
      wc: "Mitsubishi_F-2" },
    { id: "azarakhsh", n: "HESA Azarakhsh", st: "rw", nat: "Iran", mfr: "HESA", t: 1997, row: 16, dl: "reported first flight 1997",
      wc: "HESA_Azarakhsh", note: "Iran's first domestic fighter program; production numbers and status are opaque." },
    { id: "saeqeh", n: "HESA Saeqeh", st: "rw", nat: "Iran", mfr: "HESA", t: 2004, row: 16, dl: "first flight 2004",
      wc: "HESA_Saeqeh" },
    { id: "kowsar", n: "HESA Kowsar", st: "rw", nat: "Iran", mfr: "HESA", t: 2018, row: 16, dl: "unveiled 2018",
      wc: "HESA_Kowsar", note: "Claimed '100% indigenous'; outside observers read it as an F-5F with new avionics." },
    { id: "fa50", n: "KAI FA-50", st: "rw", nat: "South Korea", mfr: "Korea Aerospace Industries", t: 2011, row: 29, dl: "FA-50 first flight 2011",
      wc: "KAI_T-50_Golden_Eagle", gk: "KAI_FA-50", dsg: "Poland FA-50PL/GF, Philippines, Iraq T-50IQ, Malaysia FA-50M." },
    { id: "kf21", n: "KF-21 Boramae", st: "rw", nat: "South Korea", mfr: "Korea Aerospace Industries", t: 2022, row: 29, dl: "first flight 2022",
      wc: "KAI_KF-21_Boramae", dsg: "Indonesia is a junior program partner (IF-X)." },

    // ── USSR: Yakovlev lane ───────────────────────────────
    { id: "yak1", n: "Yak-1", st: "su", nat: "Soviet Union", mfr: "Yakovlev", t: 1940, row: 30, dl: "first flight 1940",
      wc: "Yakovlev_Yak-1" },
    { id: "yak3", n: "Yak-3", st: "su", nat: "Soviet Union", mfr: "Yakovlev", t: 1943, row: 30, dl: "first flight 1943",
      wc: "Yakovlev_Yak-3", dsg: "Flown by the French Normandie-Niemen regiment." },
    { id: "yak15", n: "Yak-15", st: "su", nat: "Soviet Union", mfr: "Yakovlev", t: 1946, row: 30, dl: "first flight 1946",
      wc: "Yakovlev_Yak-15" },
    { id: "yak38", n: "Yak-38", st: "su", nat: "Soviet Union", mfr: "Yakovlev", t: 1971.5, row: 30, dl: "first flight 1971",
      wc: "Yakovlev_Yak-38", dsg: "NATO 'Forger'; the Soviet Navy's only operational VTOL jet." },
    { id: "yak141", n: "Yak-141", st: "su", nat: "Soviet Union", mfr: "Yakovlev", t: 1987, row: 30, dl: "first flight 1987",
      wc: "Yakovlev_Yak-141", dsg: "NATO 'Freestyle'; program died with the USSR." },

    // ── USSR: MiG lane ────────────────────────────────────
    { id: "mig3", n: "MiG-3", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1940.7, row: 32, dl: "first flight 1940",
      wc: "Mikoyan-Gurevich_MiG-3" },
    { id: "mig9", n: "MiG-9", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1946.3, row: 32, dl: "first flight 1946",
      wc: "Mikoyan-Gurevich_MiG-9" },
    { id: "mig15", n: "MiG-15", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1947.9, row: 32, dl: "first flight 1947",
      wc: "Mikoyan-Gurevich_MiG-15",
      dsg: "NATO 'Fagot'; license-built as PZL Lim-1/2 (Poland) and Avia S-102/103 (Czechoslovakia); Chinese J-2 in service." },
    { id: "mig17", n: "MiG-17", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1950, row: 32, dl: "first flight 1950",
      wc: "Mikoyan-Gurevich_MiG-17", dsg: "NATO 'Fresco'; PZL Lim-5/6; Shenyang J-5 in China." },
    { id: "mig19", n: "MiG-19", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1952.8, row: 32, dl: "first flight 1952",
      wc: "Mikoyan-Gurevich_MiG-19", dsg: "NATO 'Farmer'; Shenyang J-6 outlived the Soviet original by decades." },
    { id: "mig21", n: "MiG-21", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1956, row: 32, dl: "Ye-4 first flight 1955",
      wc: "Mikoyan-Gurevich_MiG-21",
      dsg: "NATO 'Fishbed'; HAL license production in India; Czechoslovak S-106; Chinese J-7 / export F-7. Most-produced supersonic jet in history." },
    { id: "mig25", n: "MiG-25", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1964.3, row: 33, dl: "first flight 1964",
      wc: "Mikoyan-Gurevich_MiG-25", dsg: "NATO 'Foxbat'; Belenko's 1976 defection handed one to the West." },
    { id: "mig23", n: "MiG-23", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1967.3, row: 32, dl: "first flight 1967",
      wc: "Mikoyan-Gurevich_MiG-23", dsg: "NATO 'Flogger'; the MiG-27 is its ground-attack derivative." },
    { id: "mig27", n: "MiG-27", st: "su", nat: "Soviet Union", mfr: "Mikoyan-Gurevich", t: 1970.8, row: 32, dl: "first flight 1970",
      wc: "Mikoyan_MiG-27", gk: "Mikoyan_MiG-27",
      dsg: "India: license-built by HAL as the Bahadur, flown until 2019 — the type's last operator." },
    { id: "mig29", n: "MiG-29", st: "su", nat: "Soviet Union", mfr: "Mikoyan", t: 1977.8, row: 32, dl: "first flight 1977",
      wc: "Mikoyan_MiG-29", dsg: "NATO 'Fulcrum'; inherited by a reunified Luftwaffe, later sold to Poland for €1 apiece." },
    { id: "mig35", n: "MiG-35", st: "su", nat: "Russia", mfr: "Mikoyan", t: 2007, row: 32, dl: "first flight 2007",
      wc: "Mikoyan_MiG-35", dsg: "NATO 'Fulcrum-F'." },

    // ── USSR: Lavochkin + high-speed MiG lane ─────────────
    { id: "la5", n: "La-5", st: "su", nat: "Soviet Union", mfr: "Lavochkin", t: 1942.2, row: 31, dl: "first flight 1942",
      wc: "Lavochkin_La-5" },
    { id: "la7", n: "La-7", st: "su", nat: "Soviet Union", mfr: "Lavochkin", t: 1944.2, row: 31, dl: "first flight 1944",
      wc: "Lavochkin_La-7", dsg: "Kozhedub, the top Allied ace, scored most of his 62 kills in La-5s and La-7s." },
    { id: "mig31", n: "MiG-31", st: "su", nat: "Soviet Union", mfr: "Mikoyan", t: 1975.5, row: 33, dl: "first flight 1975",
      wc: "Mikoyan_MiG-31", dsg: "NATO 'Foxhound'." },

    // ── Sukhoi lane ───────────────────────────────────────
    { id: "su7", n: "Su-7", st: "su", nat: "Soviet Union", mfr: "Sukhoi", t: 1955.8, row: 36, dl: "first flight 1955",
      wc: "Sukhoi_Su-7", dsg: "NATO 'Fitter-A'; India's principal strike jet of the 1971 war." },
    { id: "su17", n: "Su-17/20/22", st: "su", nat: "Soviet Union", mfr: "Sukhoi", t: 1966.4, row: 36, dl: "first flight 1966",
      wc: "Sukhoi_Su-17", dsg: "Export Su-20/Su-22 'Fitter' flown from Peru to Poland to Syria." },
    { id: "su24", n: "Su-24", st: "su", nat: "Soviet Union", mfr: "Sukhoi", t: 1970, row: 36, dl: "swing-wing T6-2I first flight 1970",
      wc: "Sukhoi_Su-24", gk: "Sukhoi_Su-24",
      dsg: "The USSR's answer to the F-111: two seats side by side, terrain-following strike in all weather." },
    { id: "su25", n: "Su-25", st: "su", nat: "Soviet Union", mfr: "Sukhoi", t: 1974.2, row: 36, dl: "first flight 1975",
      wc: "Sukhoi_Su-25", gk: "Sukhoi_Su-25",
      dsg: "Frogfoot / Grach; Czechoslovakia, Iraq, and a dozen others; both sides of the war in Ukraine." },
    { id: "su27", n: "Su-27", st: "su", nat: "Soviet Union", mfr: "Sukhoi", t: 1977.3, row: 36, dl: "T-10 first flight 1977",
      wc: "Sukhoi_Su-27", dsg: "NATO 'Flanker'; licensed to China as the Shenyang J-11." },
    { id: "su34", n: "Su-34", st: "su", nat: "Russia", mfr: "Sukhoi", t: 1990, row: 36, dl: "first flight 1990",
      wc: "Sukhoi_Su-34", dsg: "NATO 'Fullback'; side-by-side two-seat strike Flanker." },
    { id: "su57", n: "Su-57", st: "su", nat: "Russia", mfr: "Sukhoi", t: 2010, row: 36, dl: "T-50 first flight 2010",
      wc: "Sukhoi_Su-57", dsg: "NATO 'Felon'." },

    // ── Su-27 variant lane ────────────────────────────────
    { id: "su33", n: "Su-33", st: "su", nat: "Soviet Union / Russia", mfr: "Sukhoi", t: 1987.5, row: 37, sub: 1, dl: "first flight 1987",
      wc: "Sukhoi_Su-33", dsg: "NATO 'Flanker-D'; carrier-borne from Admiral Kuznetsov." },
    { id: "su30", n: "Su-30", st: "su", nat: "Russia", mfr: "Sukhoi", t: 1992, row: 37, sub: 1, dl: "first flight 1989",
      wc: "Sukhoi_Su-30", dsg: "Su-30MKI license-built by HAL in India; MKM (Malaysia), MKA (Algeria), MK2 (Venezuela, Vietnam)." },
    { id: "su35", n: "Su-35S", st: "su", nat: "Russia", mfr: "Sukhoi", t: 2008, row: 37, sub: 1, dl: "first flight 2008",
      wc: "Sukhoi_Su-35", dsg: "NATO 'Flanker-E'; exported to China and (embargo-diverted) Iran." },

    // ── China ─────────────────────────────────────────────
    { id: "j5", n: "Shenyang J-5", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 1956.5, row: 34, dl: "first flight 1956",
      wc: "Shenyang_J-5", dsg: "Export F-5 (not to be confused with Northrop's); Poland-style license lineage from the MiG-17F." },
    { id: "j6", n: "Shenyang J-6", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 1958.8, row: 34, dl: "first flight 1958",
      wc: "Shenyang_J-6", dsg: "Export F-6 — Pakistan's mainstay of the 1971 war." },
    { id: "q5", n: "Nanchang Q-5", st: "rw", nat: "China", mfr: "Nanchang", t: 1965.4, row: 34, dl: "first flight 1965",
      wc: "Nanchang_Q-5", gk: "Nanchang_Q-5",
      dsg: "Export A-5: Pakistan, Bangladesh, Myanmar, North Korea. Served until 2017." },
    { id: "j7", n: "Chengdu J-7", st: "rw", nat: "China", mfr: "Chengdu Aircraft Corporation", t: 1966, row: 35, dl: "first flight 1966",
      wc: "Chengdu_J-7", dsg: "Export F-7 to ~14 countries; Pakistan F-7P/PG." },
    { id: "j8", n: "Shenyang J-8", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 1969.3, row: 34, dl: "first flight 1969",
      wc: "Shenyang_J-8", dsg: "The J-8II 'Finback-B' is the definitive form." },
    { id: "j10", n: "Chengdu J-10", st: "rw", nat: "China", mfr: "Chengdu Aircraft Corporation", t: 1998, row: 35, dl: "first flight 1998",
      wc: "Chengdu_J-10", dsg: "Export J-10CE to Pakistan (2022)." },
    { id: "jf17", n: "JF-17 Thunder", st: "rw", nat: "China / Pakistan", mfr: "Chengdu / Pakistan Aeronautical Complex", t: 2003.5, row: 35, dl: "first flight 2003",
      wc: "CAC/PAC_JF-17_Thunder", gk: "JF-17_Thunder", dsg: "China: FC-1 Xiaolong; PAC Kamra final assembly; Myanmar, Nigeria, Azerbaijan." },
    { id: "j20", n: "Chengdu J-20", st: "rw", nat: "China", mfr: "Chengdu Aircraft Corporation", t: 2011, row: 35, dl: "first flight 2011",
      wc: "Chengdu_J-20" },
    { id: "fc31", n: "Shenyang FC-31 / J-35", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 2016.2, row: 34, dl: "first flight 2012",
      wc: "Shenyang_FC-31" },

    // ── China: Flanker lane ───────────────────────────────
    { id: "j11", n: "Shenyang J-11", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 1998.8, row: 38, dl: "first Chinese-assembled 1998",
      wc: "Shenyang_J-11" },
    { id: "j11b", n: "Shenyang J-11B", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 2003.9, row: 38, dl: "first flight 2003",
      wc: "Shenyang_J-11", note: "Continued Flanker production with Chinese avionics and (eventually) WS-10 engines — without a Sukhoi license." },
    { id: "j15", n: "Shenyang J-15", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 2009.5, row: 39, dl: "first flight 2009",
      wc: "Shenyang_J-15", dsg: "Carrier fighter for Liaoning and Shandong." },
    { id: "j16", n: "Shenyang J-16", st: "rw", nat: "China", mfr: "Shenyang Aircraft Corporation", t: 2013.9, row: 38, dl: "first flight 2011",
      wc: "Shenyang_J-16" }
  ],

  edges: [
    // US Navy
    { f: "f4f", t: "f6f", type: "d" },
    { f: "f6f", t: "f8f", type: "d" },
    { f: "f8f", t: "f9f", type: "l" },
    { f: "f9f", t: "f9f8", type: "d" },
    { f: "f9f8", t: "f11f", type: "l" },
    { f: "fh1", t: "f2h", type: "d" },
    { f: "f2h", t: "f3h", type: "d" },
    { f: "f3h", t: "f4", type: "d" },
    { f: "f101", t: "f4", type: "l" },
    { f: "f111", t: "f14", type: "l",
      note: "The F-111B naval fiasco collapsed into the F-14 program; the AWG-9 radar and AIM-54 Phoenix carried straight over." },
    { f: "f4", t: "f15", type: "l" },

    // Hornet line
    { f: "f5a", t: "f5e", type: "d" },
    { f: "f5e", t: "yf17", type: "d",
      note: "Via Northrop's P-530/P-600 Cobra studies, an enlarged twin-engine F-5 lineage." },
    { f: "yf17", t: "f18", type: "d" },
    { f: "f18", t: "f18ab", type: "d" },
    { f: "f18ab", t: "f18cd", type: "d" },
    { f: "f18cd", t: "f18ef", type: "d" },
    { f: "f5e", t: "azarakhsh", type: "c",
      note: "Reverse-engineered from Iran's embargoed F-5 fleet — no Northrop license, no Northrop parts support." },
    { f: "azarakhsh", t: "saeqeh", type: "d",
      note: "Same reverse-engineered F-5 lineage, refined and given twin tails." },
    { f: "saeqeh", t: "kowsar", type: "d" },
    { f: "f5e", t: "fck1", type: "l", q: 1,
      note: "AIDC drew on US technical assistance and F-5 co-production experience." },

    // Lockheed lane
    { f: "p38", t: "p80", type: "l" },
    { f: "p59", t: "p80", type: "l" },
    { f: "p80", t: "f94", type: "d" },
    { f: "yf22", t: "f22", type: "d" },
    { f: "x35", t: "f35", type: "d" },
    { f: "f35", t: "f35a", type: "d" },
    { f: "f35a", t: "f35b", type: "d" },
    { f: "f35b", t: "f35c", type: "d" },
    { f: "f35a", t: "f35i", type: "d" },
    { f: "yak141", t: "f35b", type: "l",
      note: "Lockheed partnered with Yakovlev in the 1990s; the F-35B's shaft-driven lift-fan layout echoes Yak-141 lessons." },

    // Republic / Convair / GD
    { f: "p47", t: "f84", type: "l" },
    { f: "f84", t: "f84f", type: "d" },
    { f: "f84f", t: "f105", type: "l" },
    { f: "f102", t: "f106", type: "d" },
    { f: "f16", t: "f16ab", type: "d" },
    { f: "f16ab", t: "f16cd", type: "d" },
    { f: "f16cd", t: "f16ef", type: "d" },
    { f: "f16cd", t: "f16i", type: "d" },
    { f: "f16cd", t: "f2", type: "c",
      note: "The F-2 is a licensed, enlarged F-16 co-developed by Mitsubishi and Lockheed Martin." },
    { f: "f16cd", t: "fa50", type: "c",
      note: "KAI's T-50/FA-50 family was designed with Lockheed Martin assistance on F-16 lineage." },
    { f: "f16ab", t: "lavi", type: "l", q: 1 },
    { f: "f16ab", t: "fck1", type: "l", q: 1 },

    // North American lane
    { f: "p40", t: "p51", type: "l",
      note: "North American declined to license-build P-40s for Britain and offered the NA-73X instead — buying Curtiss's P-40/XP-46 data for $56,000 along the way." },
    { f: "p51", t: "fj1", type: "l" },
    { f: "fj1", t: "f86", type: "d" },
    { f: "me262", t: "f86", type: "l",
      note: "Captured German swept-wing research reached North American in 1945 and re-winged the XP-86." },
    { f: "f86", t: "cl13", type: "c" },
    { f: "f86", t: "ca27", type: "c" },
    { f: "f86", t: "f100", type: "d",
      note: "Began at North American as the 'Sabre 45' — a Sabre with 45° of sweep." },

    // F-15 family
    { f: "f4", t: "f14", type: "l", q: 1 },
    { f: "f15", t: "f15a", type: "d" },
    { f: "f15a", t: "f15b", type: "d" },
    { f: "f15a", t: "f15c", type: "d" },
    { f: "f15b", t: "f15d", type: "d" },
    { f: "f15c", t: "f15j", type: "c" },
    { f: "f15d", t: "f15e", type: "d",
      note: "The Strike Eagle grew from the two-seat airframe via the company-funded Strike Eagle demonstrator." },
    { f: "f15e", t: "f15i", type: "d" },
    { f: "f8u", t: "a7", type: "d",
      note: "Vought shortened and de-supersonicized the Crusader into a subsonic bomb truck — same layout, entirely different mission." },
    { f: "p47", t: "a10", type: "l",
      note: "A lineage of company and creed, not parts: Fairchild Republic named the A-10 for Republic's P-47, the previous great survivable ground-pounder." },
    { f: "tornado", t: "tornadoadv", type: "d" },
    { f: "mig23", t: "mig27", type: "d" },
    { f: "j6", t: "q5", type: "d",
      note: "Nanchang stretched the J-6/MiG-19 into a supersonic attacker with a new nose, internal bay, and side intakes — China's first largely indigenous redesign." },
    { f: "f15e", t: "f15k", type: "d" },
    { f: "f15e", t: "f15ex", type: "d",
      note: "Via the Advanced Eagle line (F-15SA/QA) back into USAF service." },
    { f: "f15", t: "f22", type: "l", q: 1 },

    // UK
    { f: "hurricane", t: "spitfire", type: "l", q: 1,
      note: "Rivals, not relatives — linked only by the shared Merlin engine and RAF requirement. Marked informal on purpose." },
    { f: "meteor", t: "hunter", type: "l", q: 1 },
    { f: "vampire", t: "venom", type: "d" },
    { f: "p1127", t: "harrier", type: "d",
      note: "Via the tri-service Kestrel evaluation squadron." },
    { f: "harrier", t: "seaharrier", type: "d" },
    { f: "harrier", t: "av8b", type: "d",
      note: "When the UK dropped the 'big wing' Harrier, McDonnell Douglas developed it alone as the AV-8B." },
    { f: "av8b", t: "harrier2", type: "c",
      note: "The British GR.5 is the licensed build of the American development of a British aircraft." },
    { f: "hunter", t: "p1127", type: "l", q: 1 },
    { f: "lightning", t: "tornadoadv", type: "l", q: 1 },
    { f: "tornadoadv", t: "typhoon", type: "l" },
    { f: "jaguar", t: "f1jp", type: "l", q: 1,
      note: "The resemblance is striking, but Mitsubishi's T-2/F-1 was an independent design." },

    // Sweden
    { f: "tunnan", t: "draken", type: "l" },
    { f: "draken", t: "viggen", type: "l" },
    { f: "viggen", t: "gripen", type: "l" },

    // France / Israel / South Africa
    { f: "ouragan", t: "mystere4", type: "d" },
    { f: "mystere4", t: "supermystere", type: "d" },
    { f: "mystere4", t: "mirage3", type: "l",
      note: "Via the MD.550 Mystère-Delta demonstrator that became the Mirage I." },
    { f: "mirage3", t: "mirage5", type: "d" },
    { f: "mirage3", t: "miragef1", type: "d" },
    { f: "mirage3", t: "mirage2000", type: "l" },
    { f: "mirage2000", t: "rafale", type: "l" },
    { f: "mirage5", t: "nesher", type: "c",
      note: "Built from Mirage 5 drawings after the 1969 French embargo — the classic unlicensed copy, with Swiss-sourced plans in the story." },
    { f: "nesher", t: "kfir", type: "d" },
    { f: "kfir", t: "lavi", type: "l" },
    { f: "mirage3", t: "cheetah", type: "d",
      note: "Rebuilt from South African Mirage III airframes." },
    { f: "kfir", t: "cheetah", type: "l",
      note: "IAI assistance and Kfir-style canards, nose, and systems under apartheid-era sanctions." },
    { f: "lavi", t: "j10", type: "l", q: 1,
      note: "Widely alleged Israeli assistance; Chengdu maintains the J-10 is indigenous. Disputed by design." },

    // Germany + heirs
    { f: "bf109", t: "s199", type: "c",
      note: "Czech-built 109 airframes mated to Jumo bomber engines when the DB 605 stock burned." },
    { f: "bf109", t: "ha1112", type: "c",
      note: "Spanish 109s that ended up powered by the Merlin — the enemy's engine." },
    { f: "fw190", t: "ta152", type: "d" },
    { f: "me262", t: "s92", type: "c" },
    { f: "ta152", t: "marut", type: "l", q: 1,
      note: "No shared hardware — the link is Kurt Tank himself, who led both design teams." },
    { f: "marut", t: "tejas", type: "l" },
    { f: "mirage2000", t: "tejas", type: "l", q: 1,
      note: "Dassault consulted on the early LCA; the tailless delta layout shows it." },

    // Asia
    { f: "fa50", t: "kf21", type: "l" },
    { f: "f18ef", t: "kf21", type: "l", q: 1,
      note: "KF-21 configuration echoes the twin-engine US school; Lockheed Martin provided technical assistance." },

    // USSR piston + Yak jets
    { f: "yak1", t: "yak3", type: "d" },
    { f: "yak3", t: "yak15", type: "d",
      note: "Literally a Yak-3 airframe with a Jumo 004 copy slung under the nose." },
    { f: "la5", t: "la7", type: "d" },
    { f: "yak38", t: "yak141", type: "d" },

    // MiG lane
    { f: "mig3", t: "mig9", type: "l" },
    { f: "mig9", t: "mig15", type: "l" },
    { f: "me262", t: "mig15", type: "l", q: 1,
      note: "German swept-wing data plus Britain's astonishing sale of the Rolls-Royce Nene, copied as the Klimov RD-45/VK-1." },
    { f: "mig15", t: "mig17", type: "d" },
    { f: "mig17", t: "mig19", type: "d" },
    { f: "mig19", t: "mig21", type: "l" },
    { f: "mig21", t: "mig23", type: "l" },
    { f: "mig25", t: "mig31", type: "d" },
    { f: "mig23", t: "mig29", type: "l", q: 1 },
    { f: "mig29", t: "mig35", type: "d" },

    // Sukhoi
    { f: "su7", t: "su17", type: "d",
      note: "The Su-17 is the Su-7 with variable-geometry outer wings." },
    { f: "su27", t: "su33", type: "d" },
    { f: "su27", t: "su30", type: "d" },
    { f: "su27", t: "su35", type: "d" },
    { f: "su27", t: "su34", type: "d" },
    { f: "su27", t: "su57", type: "l" },
    { f: "mig29", t: "su27", type: "l", q: 1,
      note: "Siblings from the same PFI requirement, split into light and heavy fighters — a shared origin, not a lineage." },

    // China
    { f: "mig17", t: "j5", type: "c" },
    { f: "mig19", t: "j6", type: "c" },
    { f: "mig21", t: "j7", type: "c",
      note: "License granted in 1961, then executed without Soviet help after the Sino-Soviet split." },
    { f: "j7", t: "j8", type: "d" },
    { f: "j7", t: "jf17", type: "d",
      note: "Via the Super-7/Sabre II upgrade programs, with early Grumman and later Mikoyan consultation." },
    { f: "su27", t: "j11", type: "c" },
    { f: "j11", t: "j11b", type: "d" },
    { f: "su33", t: "j15", type: "c", q: 1,
      note: "Developed around the T-10K-3 Su-33 prototype acquired from Ukraine — no Sukhoi license." },
    { f: "j11b", t: "j16", type: "d" },
    { f: "j10", t: "j20", type: "l", q: 1 },
    { f: "f35", t: "fc31", type: "l", q: 1,
      note: "Western analysts point to F-35 design data compromised in the 2007–09 intrusions; Shenyang has never acknowledged any connection. Firmly in disputed territory." },
    { f: "a5m", t: "a6m", type: "d" },
    { f: "a6m", t: "j2m", type: "l",
      note: "Same Mitsubishi design office, opposite philosophy: Jiro Horikoshi's team traded the Zero's range and agility for climb and speed." },
    { f: "ki27", t: "ki43", type: "d" },
    { f: "ki43", t: "ki84", type: "d" },
    { f: "ki44", t: "ki84", type: "l" },
    { f: "bf109", t: "ki61", type: "l",
      note: "The Hien's Ha-40 engine was a license-built Daimler-Benz DB 601, the Bf 109E's engine; Kawasaki flew an imported 109E comparatively during development." },
    { f: "ki61", t: "ki100", type: "d" },
    { f: "ha1112", t: "ha300", type: "l",
      note: "Messerschmitt's team designed the HA-100/200/300 series at Hispano Aviación before Egypt bought the fighter project outright." },
    { f: "ha300", t: "marut", type: "l",
      note: "Brandner's Egyptian E-300 engine was flight-tested on an HF-24 Marut testbed (Mk 1BX) under the joint Egyptian-Indian program." }
  ],

  // lane labels, indexed by row
  lanes: [
    "Grumman", "Vought · McDonnell", "Northrop · Hornet", "Lockheed",
    "Republic · Convair", "North American", "Republic · Eagle", "Sabre & Eagle exports", "US attack",
    "United Kingdom", "UK · Harrier", "Sweden", "France", "France · Mirage F1",
    "Israel", "South Africa", "Egypt · Iran", "Heinkel · Dornier", "Bf 110 · Me 163", "Messerschmitt", "Avia · Hispano", "Focke-Wulf",
    "India", "Japan · Mitsubishi", "Japan · Kawanishi", "Japan · Nakajima", "Japan · Ki-44", "Japan · Kawasaki", "Taiwan", "South Korea",
    "Yakovlev", "Lavochkin", "Mikoyan-Gurevich", "MiG interceptors", "Shenyang · Nanchang",
    "Chengdu", "Sukhoi", "Flanker family", "Shenyang · Flankers", "Shenyang · Carrier"
  ],

  groups: []
};
